[package]
name        = "kaas-ui-auth"
description = "Who is asking, and what they are allowed to see."
version.workspace      = true
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
arc-swap        = { workspace = true }
humantime       = "2"
humantime-serde = { workspace = true }
openidconnect   = { workspace = true }
serde_json      = { workspace = true }
serde         = { workspace = true }
thiserror     = { workspace = true }
tracing       = { workspace = true }
utoipa        = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
url        = "2"
tokio      = { workspace = true }

[lints]
workspace = true
